name: Deploy to Auth0 staging account

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download files from the current repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install the auth0-deploy-cli
      run: npm install
  
    - name: Import changes to the Auth0 staging account
      env:
        AUTH0_CLIENT_SECRET: ${{ secrets.STAGING_AUTH0_CLIENT_SECRET }}
      run: npm run import:staging
